name: Build
on: push

jobs:
    build:
        name: Build
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true

            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: build-${{ hashFiles('**/Cargo.lock') }}

            - name: Install cargo-vcpkg
              uses: actions-rs/cargo@v1
              with:
                  command: install
                  args: cargo-vcpkg
            - name: Build vcpkg dependencies
              uses: actions-rs/cargo@v1
              with:
                  command: vcpkg
                  args: build

            - name: Build binary
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release

            - name: Upload binary
              uses: actions/upload-artifact@v2
              with:
                  name: session-0sw
                  path: target/release/session-0sw.exe
