name: Build
on: push

jobs:
    build:
        name: Build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                      bin: target/release/session-0sw
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                      bin: target/release/session-0sw.exe
                    - os: macOS-latest
                      target: x86_64-apple-darwin
                      bin: target/release/session-0sw

        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  target: ${{ matrix.target }}
                  override: true

            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}

            - name: Build binary
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release
            - name: Strip binary
              if: runner.os != 'Windows'
              run: strip ${{ matrix.bin }}

            - name: Upload binary
              uses: actions/upload-artifact@v2
              with:
                  name: session-0sw-${{ matrix.target }}
                  path: ${{ matrix.bin }}
